language: java

script:
    - mvn clean package -DskipTests=true

deploy:
  provider: heroku
  api_key:
    secure: 0026f1fb-4db4-4683-bec1-82e2e63ad131
  app: clientd
  on:
    all_branches: true
  run:
    - ./mvnw clean spring-boot:run
